### ISSUE TITLE
練習：Autoprefixerを使う

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#15]
Sassの練習じゃないけれど。

Compassとかを使っていないので、ベンダープレフィックスの付与について、考えなくておかないといけません。Sassのビルドするタスクの中に、Autoprefixerの処理をいれてください。
- 最新ブラウザの1バージョン下まで対応（もし最新のChrome42であれば41は対応する。40は対応しない。）
- IE8は例外的に対象

**Comment by mamiline6** [comment]
ありがとうございましたでしたー
閉じ
