### ISSUE TITLE
練習：圧縮したCSSも作成する

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#16]
https://github.com/murphydanger/gulp-minify-css などを使って、非圧縮なCSSと、圧縮されたCSSが生成されるようにしてみてください。

例えば`_scss/style.scss`からCSSがビルドされると `css/style.css` と `css/style.min.css`が生成される感じです。

**Comment by mamiline6** [comment]
ありがとうございました
閉じ閉じ
