### ISSUE TITLE
練習：タブっぽいものを作る

### ISSUE THREAD

**Issue by geckotang** [mamiline6/sass_practice#21]
@mamiline6 
以下の様なデザインをコーディングしてください。

![image](https://cloud.githubusercontent.com/assets/683965/8395951/29fd0e60-1dca-11e5-8961-1aef84487ecf.png)

ただし、あくまでワイヤーなので、デザイン通りにする必要はありませんし、タブとして機能する必要はありません（JSは不要）
必要な要素としては以下です。
- タブとタブに対応するコンテンツ領域
- タブが選択された時にタブとタブに対応する要素にクラスがつく（ `is-selected` とか）

ディレクトリは以下のようにしてください。

```
gulpfile.js
practice_tab/
  src/
    scss/
      style.scss
  app/
    index.html
    css/
       style.css
```
- `practice_tab/app/index.html`は普通に書いてください。
- `practice_tab/src/scss/style.scss` が `practice_tab/app/css/style.css` に生成されるようにしてください

不明点があればここできいてください

**Comment by geckotang** [comment]
- 生成元・先が変わるので、gulpfileにタスクを追加して下さい。
- 必要に応じてbrowserSyncとかも入れてよいです。

**Comment by mamiline6** [comment]
ありがとうございました！
